MODEL_REGISTRY = {
    "earthdial-4b-ms": {
        "id": "earthdial-4b-ms",
        "name": "EarthDial-4B-MS",
        "provider": "MBZUAI Oryx",
        "architecture": "Multimodal Remote-Sensing Vision-Language Model with Native Multispectral Support",
        "version": "4B-MS",
        "capabilities": [
            "single_image_vqa",
            "multispectral_interpretation",
            "scene_understanding",
            "land_cover_identification",
            "object_detection",
        ],
        "tasks": [
            "single_image_vqa",
            "captioning",
            "grounding",
            "scene_understanding",
        ],
        "modalities": ["optical", "multispectral"],
        "worker_env": "EARTHDIAL_WORKER_URL",
        "description": "Authoritative 4B-parameter remote-sensing VLM with native multispectral GeoTIFF support, supporting conversational VQA, scene interpretation, and grounded EO analysis.",
    },
    "geochat-7b": {
        "id": "geochat-7b",
        "name": "GeoChat-7B",
        "provider": "MBZUAI Oryx",
        "architecture": "Grounded Remote Sensing Vision-Language Model (LLaVA-adapted)",
        "version": "7B (Legacy)",
        "capabilities": [
            "single_image_vqa",
            "captioning",
            "grounding",
        ],
        "tasks": [
            "single_image_vqa",
            "captioning",
            "grounding",
        ],
        "modalities": ["optical"],
        "worker_env": "GEOCHAT_WORKER_URL",
        "description": "Legacy grounded vision-language model tailored for remote sensing VQA and bounding expression grounding (retained for backward compatibility).",
    },
    "prithvi-eo-2.0": {
        "id": "prithvi-eo-2.0",
        "name": "Prithvi-EO-2.0",
        "provider": "IBM Research / NASA / Jülich",
        "architecture": "Temporal Vision Transformer Foundation Model (300M)",
        "version": "2.0-300M",
        "capabilities": [
            "temporal_change",
            "multispectral",
            "vegetation",
            "multitemporal_analysis",
            "flood_mapping",
            "land_cover",
        ],
        "tasks": [
            "temporal_change",
            "vegetation",
            "multispectral",
        ],
        "modalities": ["optical", "multispectral"],
        "worker_env": "PRITHVI_WORKER_URL",
        "description": "Advanced open-source Earth Observation foundation model trained on global HLS multispectral time-series data for change detection, crop dynamics, and ecological forecasting.",
    },
    "terrafm": {
        "id": "terrafm",
        "name": "TerraFM",
        "provider": "Terra Foundation / OpenEO",
        "architecture": "Multimodal Optical + SAR Sensor Alignment Network",
        "version": "1.0",
        "capabilities": [
            "optical_sar",
            "multisensor",
            "land_cover_classification",
            "terrain_mapping",
            "built_up",
        ],
        "tasks": [
            "optical_sar",
            "multisensor",
            "built_up",
        ],
        "modalities": ["optical", "sar"],
        "worker_env": "TERRAFM_WORKER_URL",
        "description": "Multisensory foundation model fusing optical spectral indices with synthetic aperture radar backscatter for built-up and land cover characterization.",
    },
    "closp": {
        "id": "closp",
        "name": "CLOSP",
        "provider": "CLOSP Research (DarthReca)",
        "architecture": "Contrastive Language Optical SAR Pretraining (ResNet / ViT)",
        "version": "1.0",
        "capabilities": [
            "optical_sar",
            "cross_modal_alignment",
            "similarity_retrieval",
            "flood_mapping",
            "structural_damage",
        ],
        "tasks": [
            "optical_sar",
            "retrieval",
            "cross_modal_alignment",
        ],
        "modalities": ["optical", "sar"],
        "worker_env": "CLOSP_WORKER_URL",
        "description": "Contrastive multimodal bridge aligning natural language descriptions with paired Sentinel-1 SAR and Sentinel-2 optical observations.",
    },
    "vista": {
        "id": "vista",
        "name": "VisTA",
        "provider": "VisTA EO Consortium",
        "architecture": "Spatio-Temporal Attention Network",
        "version": "1.0",
        "capabilities": [
            "temporal_change",
            "change_qa",
            "visual_grounding",
        ],
        "tasks": [
            "temporal_change",
        ],
        "modalities": ["optical"],
        "worker_env": "VISTA_WORKER_URL",
        "description": "Visual Spatio-Temporal Attention network specialized in longitudinal optical change detection and urbanization tracking.",
    },
    "deterministic-spectral-analysis": {
        "id": "deterministic-spectral-analysis",
        "name": "Deterministic Spectral Analysis",
        "provider": "SatQuery Algorithmic Engine",
        "architecture": "Deterministic Band Math & Spectral Indices",
        "version": "1.0",
        "capabilities": [
            "vegetation",
            "temporal_change",
            "spectral_index",
            "ndvi",
        ],
        "tasks": [
            "vegetation",
            "temporal_change",
            "spectral_index",
        ],
        "modalities": ["optical", "multispectral"],
        "worker_env": None,
        "description": "Deterministic spectral index computed directly from surface reflectance bands without foundation model inference.",
    },
}